#ifndef SWORDDECORATORPLUGIN_GLOBAL_H
#define SWORDDECORATORPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SWORDDECORATORPLUGIN_LIBRARY)
#  define SWORDDECORATORPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SWORDDECORATORPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SWORDDECORATORPLUGIN_GLOBAL_H
