#ifndef BOX2DSIMULATORPLUGIN_GLOBAL_H
#define BOX2DSIMULATORPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BOX2DSIMULATORPLUGIN_LIBRARY)
#  define BOX2DSIMULATORPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BOX2DSIMULATORPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BOX2DSIMULATORPLUGIN_GLOBAL_H
