#ifndef SQUAREBLOCKBUILDERPLUGIN_GLOBAL_H
#define SQUAREBLOCKBUILDERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SQUAREBLOCKBUILDERPLUGIN_LIBRARY)
#  define SQUAREBLOCKBUILDERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SQUAREBLOCKBUILDERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SQUAREBLOCKBUILDERPLUGIN_GLOBAL_H
