#ifndef BLOKINTERFACES_GLOBAL_H
#define BLOKINTERFACES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BLOKINTERFACES_LIBRARY)
#  define BLOKINTERFACESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BLOKINTERFACESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BLOKINTERFACES_GLOBAL_H
