#ifndef PYRAMIDBLOCKBUILDERPLUGIN_GLOBAL_H
#define PYRAMIDBLOCKBUILDERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PYRAMIDBLOCKBUILDERPLUGIN_LIBRARY)
#  define PYRAMIDBLOCKBUILDERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PYRAMIDBLOCKBUILDERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PYRAMIDBLOCKBUILDERPLUGIN_GLOBAL_H
