#ifndef BLOKSCOREPLUGIN_GLOBAL_H
#define BLOKSCOREPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BLOKSCOREPLUGIN_LIBRARY)
#  define BLOKSCOREPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BLOKSCOREPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BLOKSCOREPLUGIN_GLOBAL_H
